application:
  subdomain: groupoffice
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://groupoffice:80/
services:
  groupoffice:
    # upstream: intermesh/groupoffice:25.0.113
    image: docker.1ms.run/intermesh/groupoffice:25.0.113
    environment:
      - MYSQL_USER=groupoffice
      - MYSQL_PASSWORD={{ stable_secret "groupoffice_db_password" }}
      - MYSQL_DATABASE=groupoffice
    depends_on:
      - db
    binds:
      - /lzcapp/var/godata:/var/lib/groupoffice
      - /lzcapp/pkg/content/etc/groupoffice:/etc/groupoffice
      - /lzcapp/var/gostudio:/usr/local/share/groupoffice/go/modules/studio
    setup_script: |
      mkdir /home/groupoffice
      chown -R www-data:www-data /var/lib/groupoffice /etc/groupoffice /usr/local/share/groupoffice/go/modules/studio /home/groupoffice
  db:
    # upstream: library/mariadb:11.8
    image: docker.1ms.run/library/mariadb:11.8
    environment:
      - MYSQL_ROOT_PASSWORD={{ stable_secret "groupoffice_root_password" }}
      - MARIADB_AUTO_UPGRADE=1
      - MYSQL_USER=groupoffice
      - MYSQL_PASSWORD={{ stable_secret "groupoffice_db_password" }}
      - MYSQL_DATABASE=groupoffice
    binds:
      - /lzcapp/var/dbdata:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - healthcheck.sh --connect --innodb_initialized
      start_period: 30s
